# Generated by Django 3.1.7 on 2021-04-03 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cats', '0003_add_comment_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('liked_cats', models.ManyToManyField(to='cats.Cat')),
                ('liked_titles', models.ManyToManyField(to='cats.Title')),
            ],
        ),
    ]
