# Generated by Django 3.1.7 on 2021-04-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_add_is_reported_cat'),
        ('users', '0002_add_validator_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_cats',
            field=models.ManyToManyField(to='cats.Cat'),
        ),
    ]
