# Generated by Django 3.1.7 on 2021-04-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_add_is_reported_cat'),
        ('users', '0003_add_liked_cats_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_titles',
            field=models.ManyToManyField(to='cats.Title'),
        ),
    ]
