# Generated by Django 3.1.7 on 2021-05-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0007_add_user_to_title'),
        ('users', '0003_addAbstracUser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liked_cats',
            field=models.ManyToManyField(related_name='user_set', to='cats.Cat'),
        ),
        migrations.AlterField(
            model_name='user',
            name='liked_titles',
            field=models.ManyToManyField(related_name='user_set', to='cats.Title'),
        ),
    ]
