# Generated by Django 3.1.7 on 2021-04-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='is_reported',
            field=models.IntegerField(default=0),
        ),
    ]
