# Generated by Django 3.1.7 on 2021-04-11 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_add_comment_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='is_reported',
            new_name='reported_counts',
        ),
    ]
