# Generated by Django 3.1.7 on 2021-04-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_change_is_reported_to_reported_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
    ]
